version: '3.8'

services:
  shop_app:
    build:
      context: .  
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"
    
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    command: /bin/bash -c "dotnet Shop.dll"
      
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=Sweet_Shop;Username=postgres;Password=12345
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=супер_секретний_ключ_мінімум_32_символи
      - Jwt__Issuer=ShopApp
      - Jwt__Audience=ShopUsers
      - RabbitMQ__Host=rabbitmq
      
    restart: on-failure
    
  postgres_db:
    image: postgres:15-alpine
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: Sweet_Shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Sweet_Shop"]
      interval: 5s  
      timeout: 5s  
      retries: 10  
      start_period: 10s 
      
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: always

volumes:
  postgres_data: